name: GUI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            ninja-build \
            g++-14 \
            qt6-base-dev

      - name: Configure
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          cmake -S . -B build \
            -DBUILD_CLI=OFF \
            -DBUILD_GUI=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja

      - name: Build
        run: cmake --build build